---
#Provivioning AWS
- name: Create AWS resources
  hosts: localhost
  connection: local
  gather_facts: False
  tasks:
  - name: Create a security group
    ec2_group:
      name: devops
      description: "Ansible Security Group"
      region: "us-east-1"
      vpc_id: "vpc-89f351f1"
      aws_access_key: "AKIAIAUSEJYJ7JFLKYAQ"
      aws_secret_key: "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"
      rules:
        - proto: all
          cidr_ip: "10.0.2.15/32"
        - proto: all
          group_name: devops
      rules_egress:
        - proto: all
          cidr_ip: 0.0.0.0/0
    register: firewall
  - name: Create an EC2 instance
    ec2:
      aws_access_key: "AKIAIAUSEJYJ7JFLKYAQ"
      aws_secret_key: "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"
      key_name: "mohit_firstkeypair"
      region: "us-east-1"
      group_id: "{{firewall.group_id}}"
      instance_type: "t2.micro"
      image: "ami-97785bed"
      wait: yes
      volumes:
        - device_name: /dev/sda1
          volume_type: gp2
          volume_size: 100
          delete_on_termination: true
      exact_count: 1
      count_tag:
         Name: aws-demo
      instance_tags:
         Name: aws-demo
    register: ec2
